# Generated by Django 2.2.16 on 2023-03-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230330_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Укажите адрес для страницы задачи. Используйте только латиницу, цифры, дефисы и знаки подчёркивания', max_length=100, unique=True, verbose_name='Адрес для страницы с задачей'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Значение по-умолчанию', help_text='Дайте короткое название задаче', max_length=100, verbose_name='Заголовок'),
        ),
    ]
